name: langkhach270389-Scripting-sync
on:
  schedule:
    - cron: '48 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-langkhach270389-Scripting-tree-master
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync langkhach270389-Scripting-tree-master
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/langkhach270389/Scripting.git"
          source_branch: "master"
          destination_branch: "langkhach270389-Scripting"
          github_token: ${{ secrets.PAT }}