name: Youthsongs-QuantumultX-sync
on:
  schedule:
    - cron: '51 */3 * 1 *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-Youthsongs-QuantumultX
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync Youthsongs-QuantumultX
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Youthsongs/QuantumultX.git"
          source_branch: "main"
          destination_branch: "Youthsongs-QuantumultX"
          github_token: ${{ secrets.PAT }}
